### ISSUE TITLE
The model selection download on the landing page is unacceptably constraining/small

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#175]
The model selection download on the landing page is unacceptably constraining--it has been alright for a handful of models while experimenting, but when more people and brought on and more models are created, there is no good way to find the model.

The solution here is to replace the dropdown with a sortable table for the various annotations (think the show_models() command in geneontology/noctua-repl), with a text search box to eliminate rows (think the amigo filter filter box). This should go nicely to the hundreds?

While I think this is necessary now, it is obviously still a stopgap measure for a better long-term solution--this will not scale to the thousands and beyond.

**Comment by kltm** [comment]
Have already had some schema/golr prep changes for something to tide us over.

**Comment by cmungall** [comment]
What are the next steps? AmiGO browsing is great but involves a few too many steps if I already know my title. Would an autocomplete on title or some concatenation of title plus some other attributes be sensible?

**Comment by kltm** [comment]
I have that working locally right now, but chickened out pushing it to dev. It works well enough that it might be nice to have as a search box here and there, but I think some kind of filter table would be more intuitive and effective (probably a non-AmiGO widget). I can have a demo up for those later on.

**Comment by ukemi** [comment]
I think we need to come up with a naming convention for models and then try to categorize them in some logical way. Is there a way we can use the structure of the ontology to bin the models?

**Comment by cmungall** [comment]
This partly belongs in the to be written annotators guide, but it's partly a tooling issue. E.g. there could be some assistance from Noctua (and when seeding the title should be automatic).

As a rough guide:

 * Models that correspond to a single paper use the title of the paper
 * If the model is derived from multiple papers but uses a figure from one paper as a central backbone, use the title of that paper
 * Models made by the ontology group to represent the canonical version of a cellular process use the name of the process plus the species (or higher taxon, when we get to the ability to do this)
 * Don't encode status in the title (e.g. "draft"), we have annotation properties for these. Same for curator name, etc
 * Models that are never intended for public consumption can have curator-specific information in the title (e.g. "consistency exercise")
 * Err on the side of being too long rather than too short

**Comment by kltm** [comment]
At least for the AmiGO part of discovery, the since the models are largely disassembled and have the annotations (the OWL ones here) available, it should be pretty easy to filter through them.

**Comment by cmungall** [comment]
Looks like this is much improved. Do you want to requests in this ticket? E.g. if we want a column to make it easy to filter for models created by me or a certain curator

**Comment by kltm** [comment]
Well, there is an issue here. You'll notice that you can do this in the "Select" box two sections down. This is because the solr documents are two different set--the periodic long runner OWLTools based one and the FAM driven cheap-and-fast service (epione). At this point, epione does not parse out name, but that could be added.

**Comment by kltm** [comment]
For a final pass of the first iteration, we'll also want to add model state, as well as contributor(s).

**Comment by kltm** [comment]
Well, the long-term solution will be GOlr driven tables/searching (we can even do that now, but it makes the interface rather more intimidating and the tables look fine now), but there will be a gap there as they will not be able to detect recently modified but not saved. I think that's not a big deal, especially as we consider autosave.

For the time being though, as long as epione is active, this should be good (probably up throught hundreds and maybe into thousands).
