### ISSUE TITLE
Create an author review tool

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#184]
This may supersede some previous instructions given to @jnguyenx - still at question stage

Context:
http://wiki.geneontology.org/index.php/Proposal_for_Author_Feedback_for_annotations

Basic idea - authorized curator imports a set of publications into a model (exactly as #181)

Next step is they click a button to generate a 'survey form'. The exact details of the SF TBD, but basically it's just a list of all assertions about a gene and a yes/no/maybe checkbox. The question is as follows. the curator would like to send a link to the survey to the author of the paper. But we don't want to have a one-off login. Can we have it such that Barista will recognize a URL generated by the system that is tied to this one model?

After the original author clicks yes/no/etc, these can be added as annotations on each of the corresponding edges; e.g. approved_by=Name

I will share a google doc that explains more

**Comment by cmungall** [comment]
cc @rbalakri

**Comment by kltm** [comment]
@cmungall , that would fight with the way that barista works; from the doc, this is a fairly complicated control pattern. The right way might be to have a separate service that is unprotected. Another approach might be rotating daily robo-tokens, but I think that would be a bad idea.

**Comment by kltm** [comment]
Looking at this from a not-sleep-deprived perspective, essentially what would be needed would be a way of creating temporary users, essentially side-loading information from the user.yaml metafile. IIRC, the initial formulation that I didn't like (https://github.com/geneontology/noctua/issues/184#issuecomment-136150727) was that these would be /anonymous/ users; talking with Chris, there is no need for anonymity. An implementation might look like:

* a barista interface allows the creation of temporary new users
 * input: name, email address (md5ed by barista), ORCID if available; munged UUID for user created
* naturally, this interface needs to be protected; at least only for logged-in users
 * this interface would also have to be available programmatically, so that will take some work to make sure that only authorized users can do this
 * these tmp users will not be able to renew themselves
* std login session have a window of a week
* tmp users would have window of a month
* there will have to be a new shadow field (not apparent in users.yaml) that is essentially "noctua-model-lock": if the field exists, the user can only access models in that list; these tmp users *always* have this field
 * there will also have to be an additional shadow field along the lines of "noctua-temporary-user: true", with a false implied by default

Open questions then:

* who has permission to (basically) give arbitrary people permission to edit arbitrary models
* it looks like barista is needing a finer-grained permission system, or can this be avoided (please!)?

This will mean making some of the UIs in Barista a little more robust, and take some of the login and logout bits away from noctua (IIRC).

We'd also have to more serious implement session lengths (currently the lifetime of barista itself, although there is timeout code in there), and they'll need to be preserved across reboots. Ideally, I'd like to avoid yet another server floating around, so a node-friendly acid embedded local file-based db (BDB or SQLite?).

**Comment by kltm** [comment]
We're revisiting permissions for geneontology/go-site#105, so I might start adjusting the permission to me more granular sooner rather than later.

**Comment by kltm** [comment]
Note of older ticket to @tmushayahama , @cmungall

**Comment by vanaukenk** [comment]
Not actively being worked on; closing for future development of community curation tools.
