### ISSUE TITLE
Allow curators to add NOT qualifiers to all triples/relations

### ISSUE THREAD

**Issue by thomaspd** [geneontology/noctua#218]
In all places where a relation can be specified, curators should be able to check a box to indicate the NOT qualifier.  This will also need to be saved in the OWL representation.

**Comment by cmungall** [comment]
We'll use  [NegativePropertyAssertions](http://www.w3.org/TR/owl2-primer/#Object_Properties) for this. We'll need to extend minervaJSON to include an extra flag for this.

Note: the resulting axiom is weaker than a statement that says something like "human Shh never has transmembrane activity". This is perhaps desirable, since the ability of a curator to make statements like this can have non-local effects on other models rendering them inconsistent. We *could* explore the ability to make the stronger statements, but I'm not sure this is a good idea. I think it better to have local interpretations of the stronger statements for the purposes of detecting potential inconsistencies.

**Comment by balhoff** [comment]
It's more complicated, but more accurate modeling with complement wouldn't affect other models:

[a 'foo'] Type (not (enables some 'peroxidase activity'))

It's only talking about that instance of 'foo'. I'm not really sure how you would do this without making everyone write class expressions. I guess instance graphs could be converted to negated class expressions as long as there aren't any cycles.

**Comment by kltm** [comment]
If the pattern is general, the UI would completely paper that over.

**Comment by cmungall** [comment]
@balhoff - I agree this is preferable, and just right for strength. It can be used to check for inconsistency within a model (which would be a nice feature).

> I guess instance graphs could be converted to negated class expressions as long as there aren't any cycles.

Yes, @kltm says it should be easy to have a UI function that creates a class expression (formally, a Most Specific Subsuming Class Expression, MSSCE) from the instance to be negated. We would also need a way to create the instances again, e.g. if it were to be negated. It may be more straightforward to simply make the NegativePropertyAssertion and have the server elect to treat as a stronger interpretation

**Comment by kltm** [comment]
Had a little talk with @cmungall about this and we tried to demo of a couple of different methods mentioned here. It turns out that some of the basic work has been done for the class expression based ones.

![screenshot_2017-08-24_16-47-08](https://user-images.githubusercontent.com/2687900/29693662-eb22f88c-88eb-11e7-84ed-fcd662ef539c.png)

The leftmost (and the middle) is the suggestion from @balhoff https://github.com/geneontology/noctua/issues/218#issuecomment-306671655 . While mostly supported by what we have, we decided that the transformation from the left to the SVF construction in the middle might be 1) a little tricky and 2) be a little confusing for curators. The REPL was:

```
svf = new class_expression()
svf.as_svf('RO:0002327', 'GO:0022008')
ce = new class_expression(null)
ce.as_complement(svf)
reqs = new minerva_requests.request_set('ABC', model_id, 'action')
reqs.add_individual(ce)
manager.request_with(reqs, model_id)
```

On the right is a slightly different statement that still gives the curators some power of negation. This formulation is very easy to work with and could be added at short notice:

```
ce = new class_expression()
ce.as_complement('GO:0022008')
reqs = new minerva_requests.request_set('ABC', model_id, 'action')
reqs.add_individual(ce)
manager.request_with(reqs, model_id)
```

Both of the ones listed so far have some render issue in the client (apparent when trying to open the node), but appear to be properly functional in responses and in the generated OWL.

The final method would be to have the negation on the edges, but that would require more plumbing changes and coordination.

**Comment by kltm** [comment]
Also note that we'll have to have something analogous in SAE.

**Comment by kltm** [comment]
And we'll need to check the GAF output.

**Comment by kltm** [comment]
@cmungall @balhoff 
I now have the addition of NOT class expressions for the ubernoodle and in the CE part of the modal pop-ups. I wanted to pass it on to somebody else to check for how this affects the GAF output, etc.

E.g. http://noctua-dev.berkeleybop.org/editor/graph/gomodel:55ad81df00000001

**Comment by cmungall** [comment]
This ticket has useful discussion for historic purposes but not useful as current summary of what needs done. Replaced by #524
