### ISSUE TITLE
Create new individual-level workbench workflow for individual F/P/C/gene products

### ISSUE THREAD

**Issue by mugitty** [geneontology/noctua#224]
Update Noctu as follows:
- User left clicks green button on an Annoton to bring up Edit dialog box.
- Under Other operations sections, create 3 buttons to bring up update Function, update Process and update Cellular component.
- When user clicks on one of the update buttons, system will bring up gene products with annotations for function, process or cellular components (based on button selected).  If annoton does not have a molecular function that is enabled by a gene product, then system does not bring up list of gene products.
- User can select gene products and click on import.
- System will update existing Annoton with user selections

**Comment by kltm** [comment]
It may be that this is done at a widget level, rather than workbench, but that can be explored.

**Comment by kltm** [comment]
From email thread:
```
> Is there any reason you wanted to initially use the bioentity workbench to implement this functionality?  What is the  alternate workflow you are suggesting if we want to implement at the widget level?
```

Yes: the point of the workbench/plugin framework is to give an easy way to prototype various interactions against minerva without having to change any code in the graph editor (or any other piece of application code for any participating frontend). Workbenches/plugins are just bootstrapped code in the Noctua application environment, and can be entire applications unto themselves--making them very nice for prototyping a broad range of functionality, while at the same time not having to bother with the rather quirky and baroque UI layer that is there for the time being in the graph frontend.

If a workflow ends up being generally useful and specific to graph editing, it may be the case that it is better integrated into the graph editing interface itself. It depends. Moreover, since a fair amount of the UI is (as mentioned above) likely to be re-written in a less "meh" way, having some parts independent makes for less re-write down the road--it's easier to make the general case more specific than vice versa.

**Comment by mugitty** [comment]
This issue has a fix on https://github.com/mugitty/noctua.git branch noctua_224

**Comment by kltm** [comment]
Go ahead and rebase/merge against upstream master and submit the PR so that the diff is visible for review. I'm a little loathe to accept things this late before the meeting, especially without associated tests and development communication, but if it's just a workbench, that shouldn't be an issue this time.

**Comment by thomaspd** [comment]
This is now a priority, as we have a curator at UCL ready to start building a LEGO model from existing annotations in the GO database.  Here's a more complete description of this functionality:

Goal: the idea is to allow curators to add on to a LEGO model using annotations already in the database, similar to the Function Companion but adding to an existing annoton rather than creating a new annoton.  Function Companion will remain as is.

Interface: as it is adding to an existing annoton, it seems natural to modify the current editing interface, which is accessed by clicking on the green square in the upper left corner of an annoton.  If the annoton is linked to a gene product via enabled_by, or to multiple gene products via enabled_by some complex, then I will refer to this set of gene products as the Gene Product Set (GPS) for the annoton. Each gene product should be identified by database "bioentity" identifier. If the GPS includes at least one gene product, then there will be four new buttons in the edit box:
button 1: add Function.  This will pop up a similar interface as for the Function Companion, where a user can select from the list of any GO MF annotations for any gene product in the GPS.  The selected GO term individual will be replace the annotated "type" for that annoton, with the evidence (from the selected annotation(s)) on the enabled_by edge.
button 2: add Component.  This will pop up a similar interface as for the Function Companion, but where the ontology aspect is constrained to be CC, so the user can select from the list of any GO CC annotations for any gene product in the GPS.  The selected GO term individual will be added to the annoton, connected by  an occurs_in relation to the MF GO term individual. Evidence (from the selected annotation(s)) will be on the occurs_in edge.
button 3: add Process (part_of). This will pop up a similar interface as for the Function Companion, but where the ontology aspect is constrained to be BP, so the user can select from the list of any GO BP annotations for any gene product in the GPS.  The selected GO term individual will be added to the annoton, connected by a part_of relation to the MF GO term individual.  Evidence (from the selected annotation(s)) will be on the added edge.
button 4: add Process (regulates). This will pop up a similar interface as for the Function Companion, but where the ontology aspect is constrained to be BP (only the subset that is defined as regulates or positively/negatively regulates another BP), so the user can select from the list of any of these GO BP annotations for any gene product in the GPS.  If the GO term is regulation of X (or positively/negative regulation of X) then the BP class added to the annoton should be X, and the relation should be regulates (or positively/negatively regulates). 

Note that the cardinality of MF type is 0/1, as is the cardinality of occurs_in cellular component, and part_of biological process (but not regulates biological process, which has no cardinality constraint).  For CC and part_of BP, these can be nested, e.g. MF->[occurs_in]->CC1->[occurs_in]->CC2...->[occurs_in]->CCn.  To enable this:
- If a user tries to add a function (button 1), but there is already a non-root function selected (i.e. any term except for molecular_function) the user should be warned that the new selection will replace the current MF type and evidence.  "Warning: your selection will replace the existing Function type.  Proceed / Cancel"
- If a user tries to add a component (button 2), but there is already a non-root component for this annoton, the user should be asked to confirm that this will extend the model on top of the existing cellular component annotation(s). "Warning: your selection will extend the existing CC annotation Proceed/Cancel".  If proceed, you will need to find the current "outermost" CC annotation (tracing the chain of occurs_in), and add a new occurs_in->newCC to it, with the evidence from the selected annotation from the database.
- If a user tries to add a process using part_of (button 3), but there is already a non-root process in the model, then handle analogously to CC case immediately above.

Note that for all of these cases, the user can select multiple annotations in the Function Companion / AmiGO-like view of existing annotations, but they must all be to the same GO term.  If different terms are selected then an error message should pop up saying something like: "Error: selected annotations must be to the same GO term."  This same constraint should hold for Function Companion as well.

**Comment by ukemi** [comment]
I think this is also essentially the same as #293.

**Comment by kltm** [comment]
Hm. @ukemi, IIRC, we actually had a conversation at one point about making a generalization (possibly from this comment https://github.com/geneontology/noctua/issues/293#issuecomment-194500526 ), but when we actually sat down to model what it would look like, it turned out that BP, MF, and CC all looked fairly different and there wasn't enough commonality to make the "obvious" trivial changes to make it work.

If you read that as a dupe, I'll happily close as it never made it beyond "question".

**Comment by ukemi** [comment]
Go ahead and close it. I think it will give us essentially the same functionality.

**Comment by kltm** [comment]
Okay, I had a talk with @thomaspd this afternoon, trying to figure out the most efficient/cleanest/fastest (pick two) way of getting this moving forward so we can remove this as a block on curator work.

As outline elsewhere, to get started on this in the right way, we want to use a new framework #399 , but that will take time and we are blocking work now. Similarly, we could make faster immediate progress by skipping the new framework replacement in the core (and digging our selves in a little deeper) and just trying to bolt on a new workbench (which may or may not use a new framework), but there is a similar bit of nastiness with the workbenches (#260) where we'd like to clear it away before proceeding.

I think the overriding takeaways at this moment are: a) switching to a new framework and/or refactoring some bit will not be a quick process and b) we are blocking curator work *now*. Given this, I propose the following steps/trys to make sure we get the "best" choice we can here out the door as soon as possible (without making the codebase impossible or fall apart). In order:

1. Look at adding PubAnnotation-style (#316) communication to AmiGO; this could be a lightweight mechanism to get a workflow between the two without and need to write UI, just server code. I think that this may be a little bit out there, but such low cost it's worth looking at.
2. Look at clearing or ameliorating (#260) and bolting on a "good enough" workbench to get the curator workflow out the door, and buying us the time to do things "right". I suspect we'll end up here.
3. Find out that there are no good choices for near-future progress and commit to the deeper refactor in a new framework now. I consider this to be the worst likely case.
4. Go once more around the tree in the current framework. I think this is unlikely as the tree is likely to fall on us during the process.

For getting this out the door, @thomaspd has said that the four "buttonX" use cases above (https://github.com/geneontology/noctua/issues/224#issuecomment-252784632) should be the focus, especially CC, with the three "edge-case chaining" use cases being icing, which will make initial development that much faster.

Also, once we get something going we'll want to get curator feedback, we'll be contacting @BarbaraCzub at some point to prove feedback to make sure that any sub-optimal solution we reach still meets the functional use case.

**Comment by kltm** [comment]
I'm noticing that we seem to have an individual-level  "bioentity companion" already from work on #192 (which seemed to be early work in this direction). This companion pretty much operates exactly as the current model-level function companion, except that it kicks out additional information. That may be a good place to start--replace what code I have there with the spec above and clone it for CC.

The "football" approach is also looking pretty good. The downside is that we'd need to have a coordinated AmiGO release as well. On the upside, workflows like this could be accomplished with no additional UI code. I'll keep poking around that.

Finally, we seem to have a gap in evidence transfer. I *know* there is a conversation about this somewhere with @ukemi, but I can't find it right now. Essentially, we are unable to capture both the provenance of the original annotation and the noctua curator contribution at the same time (although having https://github.com/geneontology/noctua/issues/141 done would be helpful here). This is not helped by the fact that we have no structured way of referring to an annotation without essentially repeating all the variables in it (annotation as irritating hyperedge). I suspect that we'll need to cram something into a comment in the interim.

**Comment by BarbaraCzub** [comment]
Hi @kltm , thanks for the update. Could you please make sure that @RLovering is also made aware of the progress of this issue? We'll look forward to hearing from you with regard to the required feedback.

**Comment by kltm** [comment]
I have cleaned up the workbench deployment code (#260) and can now start on trying this as a new wrokbench.

**Comment by kltm** [comment]
Okay, a draft of button 2 done. I'll try pushing to production tomorrow afternoon/evening as the workbench changeover is quite large and there is a chance of breakage.

The pattern is in there now for more change--I'll probably try and bolt it all into one workbench.

**Comment by kltm** [comment]
I've put the new version into production. "button 2" is now available:
* select a model for editing
* make sure you are logged in
* click the green box for an annoton that has an enabled_by GP
* scroll to "GP Buddy" in "Other operations" section
* new workbench window will pop up
* select a CC item, click import.
* that item should be added, or override, the current occurs_in term

**Comment by vanaukenk** [comment]
Some/all of this functionality is available in the Noctua form-like interfaces, so closing this ticket for now.
