### ISSUE TITLE
Behavior of entity autocomplete is not consistent

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#235]
The "Add individual" box seems to have reverted back to looking at golr entity documents.

From @pdthomas:

>Autocomplete for gene products is different in the Add Function -> enabled_by than it is in the Add individual or Edit instance -> Add bundle.  In Add Function, it 
> allows one to add the organism, which is essential for finding the gene product you want.  Can the other two places use this same service too?

**Comment by kltm** [comment]
For these comments, I'll be calling the two types "GOlr" (the autocomplete run by a "standard" GOlr instance) and "NEO" (autocomplete run by the special NEO loads, probably noctua-golr.bbop.org). Changes marked by "*".

This is the state now after some correction:

* Landing
 * seeding term: GOlr; leaving since seeding is /definitely/ run from GOlr (annotations)
 * seeding species: GOlr, leaving since the NEO seems to have all the same quirks in search here
* Workbenches
 * all: GOlr; leaving as they all need annotations (of course)
* Graph editor
 * Annotation edit popup
   * evidence entry (edge): GOlr; seems to make little difference
 * Node edit popup
   * all: NEO: easier access *
WILL EDIT IN PLACE; WILL REMOVE THIS MESSAGE WHEN DONE VARIATIONS.

**Comment by kltm** [comment]
Any desired changes from this point should reference the above. Changes will be public a few minutes from now.
