### ISSUE TITLE
Various minor changes request for "Add bundle (class expression & edge pair)" on edit instance [green] 

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#240]
1. The label should change. "Bundle" is odd, and it's not really an edge pair (it's a single edge)
 2. The autocomplete on the filler works fine, but on selection it leaves the ID in there. E.g. try nucleus.
 3. I would vote for having relation first filler second. More consistent with c16, the OWL syntax, how to read the expression

Regarding 1, need to clarify what happens underneath. I think it used to make a class expression, now the CE is materialized as individuals?

**Comment by kltm** [comment]
For 1) could you suggest some better text here? (btw, husband and wife pair, as opposed to other pairings; obviously not great)
For the clarification, I'm not actually sure what you're asking here. The value contents of the autocomplete are fed in as a class expression that's used to seed the individual that's created.

**Comment by kltm** [comment]
1 nudged it a bit
2 this actually works as expected here; rather than a "quick" fix, which would make things even darker in there, I'd rather have an item more along the lines of "replace all autocompletes with something less awkward, like may a selectize-based widget". (this does work for the ubernoodle, but there is support code in there for that that is not in widgetry.js)
3 switched; i think this is right.

**Comment by kltm** [comment]
Open bits different issues now.
