### ISSUE TITLE
Provide extensive term information ubiquitously for autocompletes

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#257]
Adapt or reuse TermGenie autocomplete. Some fields that would be useful to show:
- Text definition: High priority
- Synonyms: medium
- Comment: High priority
- Direct parents: useful, particularly if they are navigable. The original Phenote UI got this exactly right.
- Direct children: as above
- Subsets/categories: see below
- OWL Equiv axioms: save for a future date

Note: I'm aware there are other autocomplete tickets but I could not find one for this specific piece of functionality discussed at the LEGO meeting. Note that the requirements specified here are intended primarily for a curation tool. It's very important for a curator to see a textual definition for a term; for an amigo user, they can just navigate to the term and see it there. However, it may be the case that a more minimal TermInfo may be useful for AmiGO.

Note on subsets: we will likely need to start restricting based on membership of subsets (or membership of complements of antislims), as well as by simple DL queries (e.g. subclass-of X, see #295). So it would be quite useful to see subset/category membership, and required to filter autocomplete results by this.

**Comment by kltm** [comment]
This may be rolled into a "redo" separate autocomplete widget, restarting from something that @jnguyenx  was working on previously.

**Comment by cmungall** [comment]
As a demonstrator case, we should test using sod2 from PomBase

As can be seem this symbol is ambiguous:
http://www.pombase.org/search/ensembl/sod2

Presumably the description field should be sufficient for the user to disambiguate

**Comment by RLovering** [comment]
a summary of the email exchanges about this:
Synonyms and gene names are not unique, if people are taught to rely on these then errors will creep into the database. When we use Protein2GO we paste the UniProt Id into the record. Having first found the appropriate ID in the UniProt database. There are times when actually you need to look in other databases (ie NCBI Gene, MGI or HGNC) to find the appropriate gene ID because the symbol you are looking for is either not in UniProt or there are so many hits returned that looking elsewhere provides confirmation/better filtering options etc. Often the full name listed in the paper is used to confirm the correct gene product ID to use. The full name might be a synonym rather than the e.g. HGNC approved name, because of the multiple roles a GP has.

When we put the protein ID into Protein2GO we then see the gene symbol associated with this record, which then means we can quickly see the ‘name’ gene product we are annotating, obviously an essential aspect to curation when you have multiple GPs to annotate on one ‘page’ and names are much easier to work with than UniProt IDs. in the long term people need a mechanism to ensure they are annotating the correct gene product. 

PomBase uses: http://www.pombase.org/search/ensembl/sod2
which provides sufficient information for the gene to be selected. 
....  we just need any way really,  to ensure that any potential ambiguity is addressed. Presenting all the annotations might be overkill....

Do you want to add ZFIN example about ZFIN curation approach here too? It doesn't feel like this fits with autocomplete?

**Comment by RLovering** [comment]
@ValWood

**Comment by ValWood** [comment]
Above seems to referring to GO term autocomplete. Later we were discussing disambiguating gene names. 2 topics?

For GO terms, we present the definition on  a side menu for the autocomplete. 
Clearly a curator also needs to see children, and comments before term selection.
We only show synonyms at this stage if this was the term used for searching (clearly marked as a synonym).

It looks like this at search point:
![canto_eg](https://cloud.githubusercontent.com/assets/7359272/16258706/f3b852b2-3856-11e6-8b9d-adb8865fb03b.jpg)

**Comment by kltm** [comment]
Likely to be rolled in some way into #261

**Comment by vanaukenk** [comment]
Closing in favor of geneontology/noctua-form#100
