### ISSUE TITLE
Most cellular location labels are lost in amigo model search view

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#272]
E.g.
http://tomodachi.berkeleybop.org/amigo/search/model_annotation

locations show with IDs not labels most of the time

(not sure if this is owltools loader or the gorl yaml config or amigo...)

**Comment by kltm** [comment]
I'd say this is probably just the fact only a few things were really available in that bad old load, and rather than trying to fix it, it was punted until we get the new loader online. You can see that the proper fields exist in amigo/metadata/model-ann-config.yaml.

Either way, there is nothing here for noctua--all amigo, owltools, and minerva.

**Comment by kltm** [comment]
See geneontology/amigo#291.
