### ISSUE TITLE
Copy-paste enabled_by IDs 

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#278]
Hi,
I wasn't sure if this AI from the Geneva meeting (#3 at the very bottom of the Google doc) ever made it into a ticket; sorry if this is a duplicate ticket.
The auto-complete list of enabled_by IDs does not carry the full complement of UniProt or MOD entity IDs, so the idea was that, in the short term, curators would be able to manually enter an enabled_by ID, if needed.  
Not sure what the long-term plan was for this, as copy-paste would potentially be error-prone.
Thanks,
--Kimberly

**Comment by cmungall** [comment]
This is correct. We will likely only have a subset of entities loaded into NEO (Noctua Entity Ontology) in the short term. However, we agreed to have the ability to directly paste in an ID. The system could possibly do a "lazy-lookup" to get the label and possibly other metadata (RNA vs protein etc) using a 3rd party service. To be discussed with @hdietze and @kltm 

If it turns out to be too complex, the brute force load everything into Neo may be the way to go

**Comment by kltm** [comment]
I believe that this is already in there--a pasted ID should be taken as-is.

**Comment by hdietze** [comment]
It is in there, kind of:
 * It *will* work for any id that is known to neo or amigo
 * It *won't* work for any other ids as minerva will fail to validate the id

**Comment by vanaukenk** [comment]
Perhaps this is an issue of getting the syntax right, but if I try to add an enabled_by entity (WB:WBGene00002163) to an existing individual, I get the following error message:

Error (error): Could not successfully handle batch request. Exception: org.geneontology.minerva.MolecularModelManager$UnknownIdentifierException. Could not validate the id: WB:WBGene00002163; your operation was likely not performed.
org.geneontology.minerva.MolecularModelManager$UnknownIdentifierException: Could not validate the id: WB:WBGene00002163 

I'm working on this model:  http://noctua.berkeleybop.org/editor/graph/gomodel:5667fdd400000696

Thanks,
--Kimberly

**Comment by vanaukenk** [comment]
WBGene00002163 does not currently have GO annotations, so from what @hdietze has said, this fits with the behavior.

**Comment by hdietze** [comment]
Summary: The copy and paste UI feature works, but the proposed underlying verification mechanism is needed, otherwise the minvera server will reject the identifier.

In general, the noctua stack needs to be capable to use/annotate with new gene product identifiers. This is probably best discussed in a different ticket.

**Comment by kltm** [comment]
Apparently not fixed in production. Looking into this now.

**Comment by kltm** [comment]
Additional flag to config: '--skip-class-id-validation'.

**Comment by kltm** [comment]
Local testing seems to show that it works as expected. Will try and roll it out to production (along with @DoctorBud's recent PR.
