### ISSUE TITLE
Automatically populate reference for root node ND annotations

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#320]
Hi,

It would be nice if Noctua could automatically populate the reference for annotations to the root nodes using the ND evidence code with GO_REF:0000015:

http://www.geneontology.org/cgi-bin/references.cgi

Thx.
--K.

**Comment by cmungall** [comment]
+1

One question is where this logic sits. The logic for defaults is related to the logic for constraints on the different "shapes" of models. E.g. We also want to restrict ND to only be root nodes.

I had originally placed this as something that happens server side:
https://github.com/geneontology/minerva/issues/40

But it may be better to have this in the client.

**Comment by cmungall** [comment]
Hmm, regarding this specific default. Does it really make sense to inherit this default from GAF editing into LEGO? Often we might want to make a placeholder instance of molecular_function. Is it really accurate or informative to say "No Data" here?

Maybe ND belongs to the world of GAFs, and in LEGO we simply omit this, but make sure it gets populated when we export GAFs

**Comment by kltm** [comment]
Back to the minerva item then?

**Comment by vanaukenk** [comment]
@cmungall - are you thinking that we wouldn't evidence root node annotations in LEGO, or we'd use a different evidence and reference from what we do now, i.e. ND and GO_REF:0000015?

**Comment by ukemi** [comment]
I have been thinking about this with respect to the load into MGI as well. At the moment, any annotations to the root node get flagged as incorrect because we have the rule that we only annotate to the root if there are no other experimental annotations. To us and the old paradigm an annotation to the root means 'we checked and we don't know anything'. I agree with Chris that we need to reconsider how this works in the LEGO world. Although I think annotations to the root node should be filtered out in the GPAD and GAF that is generated from a model (this is consistent with current practice). I'm not sure we want the same behavior in a model. I have only made these annotations for the molecular function root and I think there is evidence in these instance-based models that the gene product has some molecular function (sometimes in a specific context) based on a mutant phenotype. 
Would love to hear some feedback on this because it has impact on the GAFs, GPADs and the current rules we have for annotation representation.

**Comment by vanaukenk** [comment]
Yes, let's look at some different use cases for annotations to the root node.  In the model I was working on yesterday, I would have made an ND annotation to the MF root node as my conventional annotation, but we should look at other curation scenarios to make sure we're representing this the way we want.

**Comment by ukemi** [comment]
So a simple rule would be that an ND annotation gets reported in a GAF and in a GPAD. We should definitely look at some use cases.

**Comment by cmungall** [comment]
> @cmungall - are you thinking that we wouldn't evidence root node 
> annotations in LEGO, or we'd use a different evidence and reference 
> from what we do now, i.e. ND and GO_REF:0000015?

I don't think it's meaningful to ND a placeholder MF.

How about:

  1. a root-MF instance that has no edges in/out other than enabled_by, 
then the enabled_by gets an ND. Basically you are just saying: a gene 
product exists, so we assume there is a function (otherwise the 
translation would degrade through drift). Really the ECO class should be 
"no functional information".
  2. if the root-MF instances has causal edges in/out, then presumably 
ND makes no sense. You are ascribing a function to the gene, even if you 
can't be more specific than root-MF, in LEGO the function is spread 
across the model, and there must be some data or knowledge somewhere 
that allows you to ascribe this function.

Thing is, you'd never do 1 via the graph interface anyway. You could, 
but it would be the most spectacular overkill. Seems like a job for a 
form.

**Comment by ukemi** [comment]
This works for me. If we can make ND annotations in a form, that would be much better.

**Comment by ukemi** [comment]
Just as an update on this. Recently a curator tried to make root node annotations using the graph interface to indicte 'we looked but there was no data'. The graph generated no annotations, which is correct with the current methods, but it means that the curator will still have to go back to our old interface to create the 'unknown' annotations. Maybe we do need to put something in place that allows these, but not other root annotations in the GAF/GPAD.

gomodel:57c82fad00000322

**Comment by krchristie** [comment]
I've recently been thinking about the issue of annotations to the root too because several of my models, including this one:
* PMID-25130899-KRC Tmem163 (gomodel:5900dc7400000968)

are generating lots of annotations to "molecular_function" by some sort of experimental evidence that isn't appropriate for a root level annotation, i.e. "molecular_function" by "confocal microscopy evidence used in manual assertion". I would like for these "experimental" annotations to root to NOT be generated.

However, I would still like to be able to make root annotations with ND.

Reading through the previous comments, I'm not sure I agree with this one from Chris:
<pre>2. if the root-MF instances has causal edges in/out, then presumably
ND makes no sense. You are ascribing a function to the gene, even if you
can't be more specific than root-MF, in LEGO the function is spread
across the model, and there must be some data or knowledge somewhere
that allows you to ascribe this function.</pre>

It seems to me that we actually do this all the time. If there is mutant phenotype evidence that the gene product is involved in a process, then I may know that the gene product has a function without knowing anything about its function. If I have checked the available literature and not found any information, then I would want to indicate that I have done this comprehensive check by making the root annotation by ND. This has been SOP, even if there are sequence predictions for the function of the gene, specifically to indicate that a curator has looked (as of the annotation date) as opposed to genes that lack any annotation in that particular aspect, where no one has looked comprehensively. Many databases use these manual ND annotations to the roots of the three GO aspects as useful tags in various reports and curation to do lists, so I think it's important for this to be possible within Noctua.

Personally, I think these ND annotations need to be done in an explicit way since what this has always meant is that the curator looked for the information and was unable to find it, typically in experimental publications.

**Comment by krchristie** [comment]
Following on from discussion at the MGI GO group's meeting this morning, here's an update on this. 

With Jim's reasoning in place, the Annotation Preview now indicates that it is possible to make root level annotations with the ND (no biological data found used in manual assertion ; ECO:0000307) evidence code and using the appropriate GO_REF for the use of this evidence code (GO_REF:0000015). 

Here's the test model:
**ID**: gomodel:5966411600000387 
**Name**: TEST: unknown annotations by ND

**Comment by vanaukenk** [comment]
Automatic population of ND annotations is available in the Noctua form interfaces.
