### ISSUE TITLE
Add the ability to explode individuals

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#348]
Add an "explode individual" button to individuals. It would take the contents and sub-contents of an individual in compact or editor modes and switch it to exploded.

Likely relatively easy to implement, but would like a halo.

This seems like it would be extremely useful in a fair number of workflows that were viewed at Hinxton.

**Comment by krchristie** [comment]
@ukemi and I discussed this today and think it would be really, really useful. We were discussing a model that I had done and David suggested that I rework some of the info that is the same for 5 different individuals in the model. I said that I had already had that thought, but when I exploded the view, everything shot out of view (on a 27 inch monitor) and I basically just gave up on the idea as too tedious to go find everything in order to rearrange stuff.

**Comment by kltm** [comment]
That's moving into #340 and #173 .

**Comment by vanaukenk** [comment]
Closing for now; not actively being worked on and possibly addressed with some previous work.
