### ISSUE TITLE
Blank models sometimes show up at the top of the list of models on entry screen

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#373]
E.g.

<img width="1177" alt="screen shot 2016-11-05 at 9 54 35 pm" src="https://cloud.githubusercontent.com/assets/50745/20035457/79b7e902-a3a2-11e6-93e1-caa4cd199d98.png">

the model summary from minerva:

```
"gomodel:581cac2100000000": [ ],

...
"gomodel:581cac2100000000": {

    "modified-p": false

},
```

guessing this is the cause of the bug that we are defensive about here:
https://github.com/geneontology/minerva/pull/73

it's not clear how this can happen; it's impossible to save without a title. Even if the model is saved by the admin, all models are born with state and an initial set of dc annotations? Fairly odd.

A surface issue, potentially confusing

**Comment by kltm** [comment]
It could be. It is a _little_ odd that the creator of the model has not already had their information decorated onto contributors. As well, I'd assume that the date would be filled by the initial _create_ command, and that _development_ is default for _state_. 

@balhoff Would probably be the best place to start.

**Comment by kltm** [comment]
@balhoff Would it be the following?
In-memory minerva knows about the new model, but the graph store is what provides the meta-information; until a save has occurred, there is no model meta-information available.

**Comment by balhoff** [comment]
The meta-information is gathered from in-memory models as well. I had thought that this was entirely due to the undo directly after model creation (and so should be fixed now). Do you think there are other issues? The only remaining "problem" I know of is that if the user adds an individual directly after model creation, then undoes that, it will remove the user from the model annotations. So there will be no creator listed. But the model will still have a date and status.

**Comment by kltm** [comment]
I had not retested this one since taking the fix for #100. Looking at this now, I do not seem to be able to duplicate the original ticket, (which I didn't have pegged for being related to the undo/redo). But, as you mentioned, things are still a little weird.

To take readers to the present state, using the most up-to-date minerva, here's how to hit the problem:

1. Login and create a new model; the model now has _contributor_, _date_, and _annotation\_state_
2. Create a single individual; the model still has _contributor_, _date_, and _annotation\_state_
3. Delete the new individual; the model still has _contributor_, _date_, and _annotation\_state_
4. Undo the last op (delete individual); the model has _date_, and _annotation\_state_, but is missing _contributor_

It seems a bit like this ticket and #100. Do you know the reason for this? I'm uncomfortable with the idea that there are situations where annotations can missing.

**Comment by balhoff** [comment]
It looks like performing an undo on any model will remove the current user from the list of contributors at the model level. Find a model you have contributed to; add an individual, then undo. You will no longer be annotated as a contributor. The trouble is that a contributor annotation on the ontology is in the list of actions for each operation, and thus also in the list to undo. When the operation is undone, that annotation is removed from the ontology. A few possibilities:

1. Get rid of model-level contributor annotations and instead query for contributors across all axiom annotations in the model.
2. Never allow a contributor annotation to be removed from the model ontology.
3. Annotate the contributor annotations with a date. This would result in a large number of distinct annotations linking the model to a contributor.

**Comment by cmungall** [comment]
An additional possibility is to remove the `$ont dc:contributor $person` triple from the list of actions. Instead, bring this back as a post-processing step that happens purely on the minerva side (and as a distinct post-processing step is not subject to undo)

As for other options:

 1. I think I am OK with this. It simplifies things. I don't think queries to return model level data become significantly more complex ?
 2. This works, but it adds additional complexity and hidden functionality
 3. A bit reification-tastic but this works. As you say a lot of distinct annotations.

3 also feels like a half-baked audit trail system. I think we either stick with something lightweight (e.g. 1) or we bite the bullet and essentially store the transaction history in the model. I like this idea, but don't like the idea of doing it now.

**Comment by kltm** [comment]
@cmungall @balhoff 

I think, from the given options, I'd be most happy with with the way things are now--the rest seem like begging for trouble. The number of times that we'll run into a case where somebody 1) creates a model, 2) adds an individual, 3) deletes said individual, and 4) never touches the models ever again seems vanishingly small, if an annoying edge case.

As it stands, a user will have the annotation added initially and they should be able to find their model (this ticket), the edge case of #100 I think is not worth losing model-level contributors. Given the future of model copying, templates, etc., it would be nice to keep it simple, even if this one thing is something we won't fix.

My vote would be to close this and mark #100 as "closed" and "wontfix".

**Comment by kltm** [comment]
Going...going...gone!
