### ISSUE TITLE
Add ability to download OWL models in TTL; deprecate/remove download of RDF syntax access

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#377]
Currently, the OWL download options still use rdf syntax. As we are storing on disk in ttl, the download options should mirror it--it will make debugging easier.

@balhoff I tried to see if there was TTL access, but couldn't find any. Did I miss it, or is it something that still needs to be added to the minerva API?

**Comment by balhoff** [comment]
It is an easy one-line fix to switch the download to Turtle. The only wrinkle is that it won't be formatted quite the same as the version stored on disk. The Turtle to disk comes straight out of Blazegraph via the Sesame API, and so is very fast. However Sesame doesn't have any options for setting prefixes and grouping triples into prettier blocks. The download Turtle will come out of OWL API, since it needs to come from the in-memory model. OWL API does a nice job of formatting the Turtle. So, I think switching to Turtle away from Manchester will improve the comparability of the two files, but they won't be exact.

**Comment by kltm** [comment]
That's a shame, but I think we should just have uniform ttl output, even if it is not exactly the same.
Would you still offer rdf syntax, or would this be a switch to ttl for "owl" output?

**Comment by balhoff** [comment]
I think it might be unnecessarily confusing to offer two ontology formats for download, since both will produce exactly the same result when loaded into Protege. By the way (to avoid confusion), the current download is Manchester OWL syntax (which is not an RDF serialization), and the proposed download would be Turtle syntax (which is an RDF serialization). Providing an RDF-based syntax like Turtle also opens up use of the downloaded files to a variety of RDF tools. OWL API is pretty much the only thing that reads Manchester syntax.

**Comment by kltm** [comment]
Okay, sounds good. And right you are--nothing but format confusion for me here. I read too much in the prefixes in the header.

Getting rid of Manchester is great--it was what kept the (now late) epione from actually crunching and getting good info out of the files.

**Comment by balhoff** [comment]
I've updated the format in Minerva via https://github.com/geneontology/minerva/commit/eacddb7798d2287f67c7a785dd0fd7a79aeb294f.

**Comment by kltm** [comment]
Local testing seems to indicate that this works as expected.

**Comment by cmungall** [comment]
+1 to consistency and using turtle as the default always.

Minor terminological point: rdf isn't a syntax. turtle and rdf/xml are 
syntaxes for rdf (and owl is formally a subset of rdf)
