### ISSUE TITLE
MGI PRO ids in gpi file but not available for Noctua

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/noctua#383]
Example:  PR:000049754
Does not autocomplete /not in pick list when use as an entity for an annoton (ie, enabled by field).
There are several others.
This id was in the gpi file committed on 11/28. Not available for use 12/1. Unsure of timing of pickup from svn gpad-gpi/submission

**Comment by kltm** [comment]
We are currently doing loads weekly, over the weekend, so I believe that we'd still be in the window where it would not expected yet be in the autocomplete.

**Comment by cmungall** [comment]
I made neo build nightly.

How often does minerva restart/reload?

**Comment by kltm** [comment]
Right now, it is done manually--an outstanding issue until I switch over to systemctl.
That said, the autocomplete should be fair decoupled from that.

**Comment by cmungall** [comment]
OK, I can see why this is the case. TL;DR - the GPI stuff is caught mid-transition in our switch from svn

The URL we have is: http://geneontology.org/gpad-gpi/release/mgi.gpi.gz

This is recorded here:
https://github.com/geneontology/go-site/blob/master/metadata/datasets/mgi.yaml#L41

However, this URL has no content. This is because we are not syncing

http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/gpad-gpi/submission/
==>
http://geneontology.org/gpad-gpi/

(@kltm, at one point we were syncing with S3, but what we have on http://s3.amazonaws.com/go-public/gpad-gpi/ is out of date)

We should probably sync the directory, even though we will eventually be abandoning the whole svn/http sync mechanism

But the overall goal was to just slurp from the producer's site. @hdrabkin do you also deposit this file o the MGI ftp site? What is easiest for you moving forward?

**Comment by hdrabkin** [comment]
Yes, the mgi.gpi.gz is  on our ftp site.
If you did fetch from ftp on a scheduled basis that would do if it's easier for you guys.
Note: there is also an mgi.gpi (unzipped): don't take that; it is out of sync with the gz (the gz file is always newer).
--
Harold

**Comment by cmungall** [comment]
Can you make an edit and pull request on the mgi.yaml file?

**Comment by hdrabkin** [comment]
I'm sorry I don't feel comfortable doing this. I can't even find the file.

**Comment by ukemi** [comment]
I will see if I can do it.

**Comment by hdrabkin** [comment]
If you find the file show me. I tried searching and couldn't find.

**Comment by krchristie** [comment]
Hi @hdrabkin 

I rechecked my Noctua model (PMID-12771146-KRC ) with PRO IDs that we discussed at an MGI GO meeting. I see that my PRO ID (PR:000049741) doesn't show up in the autocomplete for the "Add annoton", "Add function", or "Add process" boxes on the left either.

However, after you have an individual for the process or function, you can get them into an "enabled by" relationship by clicking on the green box in the upper left hand corner and then entering the relationship  and PRO ID you need into the "Add edge & class expression" boxes. It doesn't show up in the autocomplete, but when you click add, the PRO ID gets added into the annoton with whatever relationship you entered. 

I suppose the fact that this box isn't actually checking that the contents I entered into the ID box were selected from the autocomplete might be considered a bug. However, I find that being able to put my PRO ID in is very useful. Perhaps instead of disallowing this behavior (allowing an ID not in the autocomplete), we could have it allowed but flagged with a warning that you could acknowledge but still use the ID, and then possibly also not allow models with that kind of warning flag to be disallowed from moving into production. 

The fact that this PRO ID isn't in Noctua probably explains why the options to export GAF or GPAD files produce the error "apparently could not resolve model".

-Karen

**Comment by hdrabkin** [comment]
Well, this should be fixed I hope by having load point to our ftp site rather than the gpad-gpi/submissions directory.

**Comment by krchristie** [comment]
Mostly I commented here because David H had asked me to submit a ticket about the fact that the options to export GAF and GPAD formats fail. Checking again this am, I realized that this is likely due to the fact that the PRO ID I used isn't actually allowed by Noctua either, so this info seemed like it belonged in this ticket. 

Still, it seems like it would be really nice for curators if they can go ahead and at least use IDs they have requested, whether from PRO, ChEBI or GO, or whatever else without having to wait for the ID pipeline to get a new ID into Noctua. That model could then be flagged in some way to indicate the "illegal" ID usage, and be disallowed from production, until the curator comes back to validate the ID once it has made it into Noctua, and then mark it for production.

**Comment by ukemi** [comment]
https://github.com/geneontology/minerva/issues/78

**Comment by ukemi** [comment]
> Can you make an edit and pull request on the mgi.yaml file?

So do we just change this to our ftp site?
https://github.com/geneontology/go-site/blob/master/metadata/datasets/mgi.yaml#L41

We did that but then backed it out.

Should we do the other files too, GPAD and GAF?

**Comment by ukemi** [comment]
Also note that 
https://github.com/geneontology/go-site/blob/master/metadata/datasets/mgi.yaml#L46
is our ftp site. Is this correct?

**Comment by hdrabkin** [comment]
yep

**Comment by cmungall** [comment]
apologies everyone just sent you on a wild goose chase..

OK, I will fix this.

**Comment by cmungall** [comment]
PR:000049741 is now in neo

next load at the w/e, it should be visible.

Apologies for the difficulties, should run smoothly from here on

**Comment by ukemi** [comment]
No worries. @balhoff   I think this 'should' take care of @krchristie 's issue too. Once I see her annotations go into the GPAD file, I will close:
geneontology/minerva#78

**Comment by krchristie** [comment]
Though the PRO term names now show up in the model for PMID-12771146-KRC, the issue of the options to export GAF or GPAD files is still NOT solved. These options still result in this error: **apparently could not resolve model**

Also, would it be possible to have a more informative error message?

**Comment by kltm** [comment]
Minerva has not yet been restarted, and the NEO for autocomplete does not pick up until over the weekend. I'll trying getting some of that through manually to test sooner.

**Comment by kltm** [comment]
Some restarts. From @hdrabkin 's example of  `PR:000049754`, it seems to resolve in Minerva now to `E3 ubiquitin-protein ligase SMURF1 phosphorylated 1 mouse Mmus`. Good there.

Looking at @krchristie 's https://github.com/geneontology/noctua/issues/383#issuecomment-265817497, I believe that this may be independent of anything to do with this ticket. For example, the scratch model also has the same problem (gomodel:55ad81df00000001):
```
apparently could not resolve model
```
@balhoff Is it possible that the fix to prevent models from accidentally being created is now blocking any kind of download? https://github.com/geneontology/noctua/issues/387 Is it possible to start creating regression tests for this kind of thing?

**Comment by hdrabkin** [comment]
FYI: Today, Noctua finds the PRO ids
Example: PR:000049754 now autocompletes

**Comment by balhoff** [comment]
@kltm I am able to get these downloads this morning. Also I am actively working on replacement GPAD exporter.

**Comment by kltm** [comment]
Okay, I believe the original issue is done here then. I've moved the download issue to https://github.com/geneontology/noctua/issues/391.
