### ISSUE TITLE
allow use of any UniProt identifier

### ISSUE THREAD

**Issue by thomaspd** [geneontology/noctua#401]
Currently only the gene product entities loaded into NEO can be used in a Noctua model.  To support use by UniProt curators, the tool needs to allow use of any valid UniProt identifier.  This need not be accessible via autocomplete (so it need not necessarily be added to NEO), as they are OK with cutting and pasting an identifier into Noctua.  Ideally, we could validate the identifier, hopefully via a UniProt web service.  Target date for implementation: end of August 2017.

**Comment by kltm** [comment]
We've taken various limits on and off the input boxes over times. At this point, the various subsystems seem to be pretty happy going whichever way. At that level, this is already done/dupe.

That said, over the last iteration, we tightened some of the input constraints due to user feedback. These can be released again, but a more core problem is trying to give everybody what they want at the same time, or making it understandable to the user when the input will/will not autocomplete and when an id can be pasted in with no further action. Some/most of this will need to wait until the UI can be properly re-written in a new framework, and is UI niceties on those tickets.

**Comment by thomaspd** [comment]
OK, thanks for the clarification.  A suggestion for UI would be to have two boxes with OR in between, one tied to NEO and autocomplete with text like "Find NEO identifier" and a second box with "Enter other identifier".
