### ISSUE TITLE
Annotations not showing in preview

### ISSUE THREAD

**Issue by emilycamozzi** [geneontology/noctua#460]
Hi, not all of my annotations are appearing in the annotation preview.   Typically, the first annoton created does and subsequent others do not.  For example,  when I add "has direct input" etc. it does not display even with evidence added.  See example: http://noctua.berkeleybop.org/editor/graph/gomodel:595a9ee700000342

I've tried adding individuals instead and changing my ordering and the problem persists.

Thanks!

**Comment by kltm** [comment]
@ukemi I was wondering if you would be available to take a look at this before we dig in--it's possible that the evidence structure is such that nothing would come out in the GPAD?

**Comment by ukemi** [comment]
Hi @emilycamozzi 

Hmmm. This all looks ok to me. I see the inputs in the annotation extensions and I see annotations to all of the functions and processes. The only odd bit is the chromatin colocalization statement. That won't result in  annotation because it is not a part of an annoton. Maybe we could chat and go over what you expected to see and why you have the colocalizes statement in the model. Some time next week?

-David

**Comment by kltm** [comment]
@ukemi thank you for helping out with this.

**Comment by emilycamozzi** [comment]
Thank you! Sounds good to me. I'm back in the office early Monday.

Emily

Sent from my iPhone

On Jul 8, 2017, at 9:31 AM, David Hill <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @emilycamozzi<https://github.com/emilycamozzi>

Hmmm. This all looks ok to me. I see the inputs in the annotation extensions and I see annotations to all of the functions and processes. The only odd bit is the chromatin colocalization statement. That won't result in annotation because it is not a part of an annoton. Maybe we could chat and go over what you expected to see and why you have the colocalizes statement in the model. Some time next week?

-David
