### ISSUE TITLE
Apparent bug in annotating a proteoform

### ISSUE THREAD

**Issue by LiNiMGI** [geneontology/noctua#462]
Hello,
when annotating  a proteoform, Noctua created two copies of annotations:
one to the specific proteoform, which is what I want;
another to the object - protein (sometimes it shows "protein" under object in the Annotation Preview window, sometimes it shows "CHEBI:36080" as object)

please see below for an example:
ID  gomodel:5966411600000361 
Name  PROtestLN 
check the annotation preview for PROtestLN

Is it a bug?

Thanks,
Li

**Comment by balhoff** [comment]
Hi, I do think this is a bug. I will look into why 'protein' is not being excluded. Thank you for the simple example!

**Comment by kltm** [comment]
http://noctua.berkeleybop.org/editor/graph/gomodel:5966411600000361

**Comment by balhoff** [comment]
I believe is due to an equivalence axiom between `PR:protein` and `CHEBI:protein`. This creates an inferred subclass relationship from all the subclasses of `PR:protein` to `CHEBI:protein`, but this isn't known to the Arachne reasoner at the time the ontology is transformed to rules.

**Comment by ukemi** [comment]
Would a simple fix be to simply create a filter to filter these annotations out? There are others that we will want to filter at some point as well, such as some annotations to the molecular function root node and 'redundant' annotations that use a regulates qualifier when an annotation to a named regulation terms is also generated. @balhoff and @kltm I'm not sure where the best step is to do this kind of thing. I would hate to put filters/limits in the logic so that we get the right annotations in the GPAD file but would lessen querying capabilities across the model. Hope this makes sense.

**Comment by balhoff** [comment]
@ukemi I do have some simple prefix filters like that in the query now, but they don't include CHEBI. In this case I'm trying something more complicated, as a general solution for this particular type of problem. I'm adding a step in Minerva startup that runs ELK to infer any new subclass relationships that can be found once all the input ontologies are merged together. Then the ontologies and these potential inferred relationships are fed into Arachne. In general Arachne assumes that the class hierarchy is pre-reasoned (this is only needed for inferring "indirectness" of types).

**Comment by vanaukenk** [comment]
@ukemi will test to see if this is still an issue.

**Comment by ukemi** [comment]
I just tested this with a proteoform of Shh and the only annotation I saw on both the annotation preview and in the GPAD export was the annotation to the proteoform. I suspect this is fixed.
