### ISSUE TITLE
Suggestion for improving Cytoscape view of Noctua models

### ISSUE THREAD

**Issue by thomaspd** [geneontology/noctua#472]
Right now, for MF nodes, the node is labeled with the MF label.  I'd suggest that you keep the node the same, but label with the name of the gene that enables it (e.g. WNT3).  

If the MF is enabled by a complex composed of multiple gene products, it should be labeled with all the gene products in the complex.

For BP's the current view looks great as is.

**Comment by kltm** [comment]
@thomaspd 
To restate your suggestion, in the case that we're in the "editor fold" and the node contains a folded GP, the GP should be on display rather than the function? I'm not sure what we'd be able to do about the case of multiple GPs without it getting a little nasty.

I think we're on the same page, but just to clarify, right now, this is intended to be exclusively a layout fixing tool, not a view(er) in its own right. Cytoscape has serious limitations about what it can do with the text inside of nodes, so I was trying to keep the focus on layout and keep all nodes, etc. and uniform as possible. Of course, if the curator does not remember what each node represents what for the model in the graph editor view, there can be problems. Maybe in the complex case then, the MF and a count of the number of GPs? I worry a little that the same node could be listed as MF or GP depending on the fold case, so chose the "always MF" as that is most analogous to what representation in the normal graph editor.

**Comment by cmungall** [comment]
ok, as a first pass we'll additionally fill in the enabled by if present, perhaps separate by "/", e.g. "kinase activity / MAPK1 Hsap".

We have some ideas about making figure-ready views but as seth says this is for configuring layout at the moment

**Comment by thomaspd** [comment]
Thanks for the clarification-- I think I'd assumed it would also be used for display.  Still, I think the gp label is enough (no MF label necessary), and if it's a complex you could just display the GO term label for the complex (the generic would be "macromolecular complex"

**Comment by kltm** [comment]
I tried several different ways, a lot either confusing myself or being subjectively ugly. I found one that seems to strike a balance, now public. Reopen if you want to go with gp-only when the `enabled by` exists in the annoton (subgraph). (Note that almost anything like a complex pretty quickly looks terrible as the cytoscape engine doesn't really deal with overflow (one of the costs of its speed).)
