### ISSUE TITLE
Protein isoform identifiers not found

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#486]
_From @BarbaraCzub on August 23, 2017 14:43_

Is there a way to make annotations to specific protein isoforms in Noctua?

E.g. Figures 1d and 1f in PMID:24121663 show that isoforms _alpha_ (UniProt ID O15350-1) and _beta_ (UniProt ID O15350-2) of TP73, which contain a transactivation domain [but not isoform _dN-alpha_ (UniProt ID O15350-8), which lacks this domain] regulate the expression of _GLS2_. 

However, when I try to add O15350-2 to my model, it allows me to select only the 'parent' UniProt ID O15350, and not a specific isoform ID.

Is there a way to make isoform-specific annotations in Noctua, or do I need to use Protein2GO to capture the information about specific isoforms?

(ref: http://noctua.berkeleybop.org/editor/graph/gomodel:5993df9e00000254)

cc: @RLovering 

_Copied from original issue: geneontology/noctua-models#36_

**Comment by kltm** [comment]
_From @cmungall on August 23, 2017 20:54_

Ah, I see what's happening here. You should have the ability to use any entity that is in your species gpi file.

However, unfortunately the goa files operate differently than other species. In particular, there are *two* GPIs produced, one for gene-level / reference / GCRP entities, the other for isoforms.

I was aware of the split for GAF/GPAD (I still think this needlessly complicates things and these should be in the same GAF, with the GCRP in col2 and the isoform in c17 where present, see https://github.com/geneontology/go-site/issues/185 for more of my moaning to @tonysawfordebi here). I had somehow neglected to remember this when specifying the pipeline for GPIs (it's there in the [goa metadata file](https://github.com/geneontology/go-site/blob/master/metadata/datasets/goa.yaml) so I have no excuse).

We made the assumption that each species would have max one GPI, I will go ahead and revise this assumption. Unfortunately you'll have to wait for up to a week.

**Comment by kltm** [comment]
_From @cmungall on August 23, 2017 21:16_

OK, changed the configuration to include isoform (so we now have all 4: GCRP, complex, rna and isoform). 

The build was successful:
https://build.berkeleybop.org/job/build-noctua-entity-ontology/lastSuccessfulBuild/

This will be visible next time minerva restarts and solr reloads, I think this w/e

**Comment by kltm** [comment]
If this requires a minerva restart, that's a manual operation. I'll pencil it in for Friday. Let me know if you want that done sooner.

**Comment by kltm** [comment]
_From @BarbaraCzub on August 24, 2017 9:18_

Thank you @cmungall and @kltm . This weekend will be fine. I'll come back to this model next week.

**Comment by kltm** [comment]
_From @BarbaraCzub on August 31, 2017 16:34_

I just tried searching for UniProt isoform IDs: 'O15350-1' or 'O15350-2' in Noctua, but still only the 'parent' protein ID (O15350) appears to be available. I suppose this minerva restart has not happened yet?

**Comment by kltm** [comment]
@BarbaraCzub @cmungall Unfortunately, while minerva has been restarted recently, the NEO build did not make it out due to issues with upstream data sources. Hopefully it will run clean this Sunday. If needed sooner, @cmungall can trigger the job manually earlier (temporarily limiting the ability of curators).

**Comment by BarbaraCzub** [comment]
Thanks @kltm . I do not need it sooner. Please do everything as scheduled. I'll try again next week.

**Comment by BarbaraCzub** [comment]
It is now possible to search for and select UniProt isoform identifiers in Noctua models, thank you!

However, there is no way to differentiate between these isoforms in the model canvas view (unless you click on a specific individual for more information), or in the annotation preview. It is only possible to get a broader overview of which annotation has been made for which isoform after having exported the GPAD (screenshots below). 

Would it be possible to display isoform information on the canvas (or at least in preview), so that it is possible to keep track of annotations being made for specific isoforms, as a model is being created?

<img width="359" alt="screen shot 2017-09-04 at 13 15 46" src="https://user-images.githubusercontent.com/16541096/30026165-a2da7588-9173-11e7-9b15-ed7ed5c60cda.png">
<img width="758" alt="screen shot 2017-09-04 at 13 15 56" src="https://user-images.githubusercontent.com/16541096/30026166-a2da567a-9173-11e7-9d48-26f49cfedca4.png">
<img width="421" alt="screen shot 2017-09-04 at 13 16 53" src="https://user-images.githubusercontent.com/16541096/30026164-a2da4676-9173-11e7-894b-8c92c8e432fd.png">
<img width="240" alt="screen shot 2017-09-04 at 13 18 41" src="https://user-images.githubusercontent.com/16541096/30026167-a2dc559c-9173-11e7-8d59-1d6c69cc0ea9.png">



CC: @RLovering

**Comment by krchristie** [comment]
I second Barbara's request to be able to see isoform info directly on the canvas (without having to go to additional clicks to see each one individually). MGI usually uses PRO IDs, which do resolve to isoforms in the canvas as in this model:
**ID: gomodel:5745387b00001874 
Name: Isoform test** 

However, it seems to me that there might be times we might need to use the UniProt ID, so it would definitely be good if UniProt isoform IDs are also visually distinguishable directly on the canvas. 

@hdrabkin Do you have anything to add on this?

**Comment by cmungall** [comment]
@tonysawfordebi - I assigned this to you (we can move this to the go-site tracker if you prefer). The goa gpis should indicate the isoform in the label field

**Comment by hdrabkin** [comment]
Yes, if other groups need a UniProt isoform, these need to be available. I think the issue is that the -2, -3's are actually NOT separate UniProt records. By using the PRO equivalents, we force the issue as these are separately mapped to a gene in our gpi.
If PRO loads a gpi (either combined organism or separated), then the PRO equivalents for at least the human ids would be in that.

**Comment by cmungall** [comment]
> I think the issue is that the -2, -3's are actually NOT separate UniProt records

These are distinct IDs/URIs. The issue is the label of the parent gene is reused. See my comment above

eg

```
UniProtKB       Q9NX53-1        EXD3    Exonuclease mut-7 homolog, isoform 5    MUT7B_HUMAN|EXD3        protein taxon:9606      UniProtKB:Q9NX53                db_subset=Swiss-Prot
```

**Comment by kltm** [comment]
This discrete Noctua issue is now complete--rolling issues forward into new topics can make the threads too long and rediscovery later on difficult. I'd vote for `go-site` as the new home.
