### ISSUE TITLE
Turtle downloads misclassify object properties as annotation properties

### ISSUE THREAD

**Issue by dosumis** [geneontology/noctua#490]
e.g.  [gomodel:59a6110e00000126](http://noctua.berkeleybop.org/download/gomodel:59a6110e00000126/owl) has:  

```ttl
###  http://purl.obolibrary.org/obo/RO_0002013
<http://purl.obolibrary.org/obo/RO_0002013> rdf:type owl:AnnotationProperty .
```

This should be 

```ttl
###  http://purl.obolibrary.org/obo/RO_0002013
<http://purl.obolibrary.org/obo/RO_0002013> rdf:type owl:ObjectProperty .
```

This causes problems when these OWL models used by downstream tools inc Protege.

**Comment by kltm** [comment]
Tagging @cmungall and @balhoff about this modeling question.

**Comment by balhoff** [comment]
We have occasionally had problems (not necessarily in Noctua) where an AnnotationProperty declaration for an ObjectProperty has slipped into an import, because OWL API will insert this anytime a property's type is ambiguous (in this case usually due to some transient technical problem). I guess the best approach would be to just remove these declarations with a SPARQL update.

**Comment by cmungall** [comment]
Is there a way to get the owlapi to work in strict mode? The auto-repair is very convenient, except when it does things like this, which I have seen a lot (outside Noctua)

**Comment by balhoff** [comment]
Okay to close this? Should be fixed now.

**Comment by kltm** [comment]
If this seems correct and all the desired changes have been applied and are live, I think it's okay to go ahead and close.

**Comment by balhoff** [comment]
Fixed via work here: https://github.com/geneontology/minerva/issues/141
