### ISSUE TITLE
Function companion and GO term autocompletes not working

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#511]
Hi,

I'm trying to work on a model but am not able to import MF annotations using the function companion as no annotations are shown.

I also can't seem to autocomplete on any GO terms in Noctua.

Thx.

**Comment by vanaukenk** [comment]
Note that the autocomplete *is* working for the Add Annoton widget, but not for the Add function or Add process widget.

**Comment by cmungall** [comment]
I wonder how long it's been like that, I don't use those two widgets too often.

The fix is quick: these should be wired up to noctua-golr, not amigo-dev-golr, I'm guessing the latter is vestigial @kltm?

**Comment by kltm** [comment]
These likely started failing on Saturday or Sunday due to a failed load. For some reason, upstream     http://purl.obolibrary.org/obo/uberon/basic.owl and/or http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl became unavailable/unparsable after the initial checks. I have restarted those loads now, so far so good.

The use of the other servers are not vestigial, as we are using the existence of annotations to populate the autocomplete, something that the "NEO" load does not provide.

**Comment by kltm** [comment]
Now getting:
```
2017-10-09 15:13:25,428 ERROR (CommandRunner:4348) could not parse:http://purl.obolibrary.org/obo/go/extensions/go-modules-annotations.owl
org.semanticweb.owlapi.io.OWLOntologyCreationIOException: connect timed out
```
retrying...

**Comment by kltm** [comment]
Now getting:
```
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: <http://purl.obolibrary.org/obo/wbphenotype.owl> Cause: connect timed out
```
retrying...

**Comment by kltm** [comment]
It looks like the loads are taking this time...will check again when finished.

**Comment by kltm** [comment]
Seems to be corrected at this point.

**Comment by vanaukenk** [comment]
Thanks!
