### ISSUE TITLE
Arachne not finding inconsistencies - complete axioms not loaded into minerva?

### ISSUE THREAD

**Issue by cmungall** [geneontology/noctua#514]
![image](https://user-images.githubusercontent.com/50745/31497418-0675a226-af2d-11e7-84e5-c002d5badceb.png)

Name: Reasoner inconsistency test

This should go red due to spatial disjointness in both GO and Uberon

**Comment by balhoff** [comment]
Arachne should be able to handle full versions of Uberon, etc., along with GO-plus, rather than import modules, if you want to go that route. But it would be safest if we first make progress on the ontology version inconsistency problems. I did a test with potential "atomic" versions of Uberon and and Go-plus and found only the small number of unsatisfiable classes I reported at https://github.com/obophenotype/uberon/issues/1382.

**Comment by vanaukenk** [comment]
@balhoff @cmungall 

Is there still more to do here?

**Comment by balhoff** [comment]
I think any further issues like this would involve specific tickets for go-lego.
