### ISSUE TITLE
Create a textual overview of a pathway (reduced information) for consumption by external resources

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#520]
This comes from discussions during the last meeting and before. Related to work on #512 .

Create a textual overview of a pathway (reduced information) for consumption by external resources. This would be similar in nature to what is provided by PomBase.

Simple statements should be easy (and fun!) to do; @ValWood , if we could go over some models at some point and talk about the proper translation, this might be a fairly simple process.

**Comment by vanaukenk** [comment]
@ValWood - could you paste in some links to examples in PomBase?  Thx.

**Comment by ValWood** [comment]
We don't actually do this.

Our textual information  is currently presented on a gene by gene basis. We are therefore representing the multiple pathways a gene is involved in simultaneously (albeit in the most non redundant form).


This is what we do currently for cdc2. Cdc2 is the major cyclin-dependent kinase and  has >240 substrates regulating pretty much every cell cycle process:

![pres](https://user-images.githubusercontent.com/7359272/31706113-bf17a200-b3df-11e7-8fb4-81056c074d60.jpg)

Eventually we would like to order by "phase" as this would be more biologist friendly.

This is about as much as you can reduce the gene specific information  to just the "knowledge" it hides redundant annotation and evididence and source. These are only one click away.

...but this is a summary of a gene not a pathway.  We then use the data captured in this way to generate the pathways.....

**Comment by ValWood** [comment]
pom1
protein serine/threonine kinase activity
  directly inhibits cdr2 involved in negative regulation of G2/M transition of mitotic cell cycle

cdr2
protein serine/threonine kinase activity
    directly inhibits wee1 involved in positive regulation of G2/M transition of mitotic cell cycle

wee1
protein tyrosine kinase activity
    directly inhibits cdc2 involved in negative regulation of G2/M transition of mitotic cell cycle

Could be summarized as

regulation of G2/M transition of mitotic cell cycle:
pom1 protein serine/threonine kinase activity directly inhibits cdr2 
cdr2 protein serine/threonine kinase activity directly inhibits wee1
wee1 protein tyrosine kinase activity directly inhibits cdc2

but  this is only one branch of the pathway. A "textual summary" of a pathway would get very complicated, and wouldn't really be so useful? It is much easier to look at a pathway diagram,  if the diagram is clear you don't need to read  any text.

You need a textual summary on a gene page because a gene product does lots of things  and it is not possible to represent all pathways simultaneously in a figure (cdc2 would nave >200 output arrows )

Maybe I am not understanding what you are trying to achieve?

**Comment by kltm** [comment]
@ValWood I think we're still trying to understand what we're trying to achieve as well. More generally, we're looking at how GO-CAM information can be consumed downstream. From previous conversations, the textual representation was floated, but not really explored, which is what we're trying to do here.
Intuitively, I'd agree that trying to represent a model in its entirety would be a bit messy; I have no feeling for how useful it might be.
For aggregating all GO-CAM information from the perspective of a GP, that would naturally be much much easier, and if useful, fairly easy to provide.

**Comment by ValWood** [comment]
> For aggregating all GO-CAM information from the perspective of a GP, that would naturally be much much easier, and if useful, fairly easy to provide.

Should already be in the exported gaf?

**Comment by kltm** [comment]
Yes. However, GAFs are not comprehensive and some information is obscured with the annotation extensions. I think it's safer to base any creation on the GO-CAMs more directly, or their direct products. 
Although, that may vary by the use case.

**Comment by ValWood** [comment]
Rather than a textual overview of a pathway, resources probably only need a consistent way to link to pathway models, and to extract gene specific information.
I’m not sure that it is useful to describe the model in text.

**Comment by kltm** [comment]
Fair enough! This would likely be provided by default in the GOlr queries that will provide, so let's call this closed.
