### ISSUE TITLE
Add ZFA to be used in Noctua

### ISSUE THREAD

**Issue by sabrinatoro** [geneontology/noctua#541]
We would like to be able to use anatomy terms from the Zebrafish Anatomy Ontology (ZFA) when making zebrafish annotations. 
Could you please add the Zebrafish Anatomy Ontology (ZFA) to Noctua? 

ZFA IRI: http://purl.obolibrary.org/obo/zfa.owl

**Comment by kltm** [comment]
@cmungall This would just need to be added to the NEO load then, right?

**Comment by cmungall** [comment]
Yes, it would go into go-lego (but not neo, which is just the entities).

We will need to check that the merge of uberon and zfa introduces no inconsistencies. This has been a problem in the past - uberon has very strict notions about distinctions between spaces and structures for example. We encode these constraints as OWL axioms. If the merge introduces these then we get inconsistent models; similar to if GO had parts of both nucleus and cytosol. 

We used to have some detailed reporting on these inconsistencies but there was no incentive to fix, I think this is a good opportunity. Rather than trying to explain all in one ticket maybe we can set up a call with @balhoff @cerivs @ybradford. We went through a similar process bringing emapa in.

**Comment by balhoff** [comment]
In the meantime it would be possible to use the ZFA bridge I created for Upheno, such that ZFA itself provides terms to add to the model, but axioms from the Upheno ZFA bridge are used for reasoning in Noctua (tighter integration with RO). The only problem with this is that there is a potential for confusion when comparing reasoning results with expectations from ZFA (this may be only a minor problem in some edge cases though).

**Comment by sabrinatoro** [comment]
@balhoff @cmungall 
What is the status of this ticket? Is there anything you still need from ZFIN? 
Thank you!

**Comment by balhoff** [comment]
@ybradford and I corresponded further about some incompatibilities between Uberon and ZFA that were in addition to the 'material entity'/'immaterial entity' distinctions. I think she was going to look through them and see how challenging it would be to align.

**Comment by ybradford** [comment]
@balhoff  I wasn't aware that the incompatibilities between Uberon and ZFA were the issue. In the email from 4/17 the issue was Immaterial -> Material issues: 
ZFA:0001717 ! pillar of the semicircular canal  ZFA:0000431 ! semicircular canal
ZFA:0000233 ! lower oral valve  ZFA:0000695 ! labial cavity
ZFA:0000451 ! upper oral valve  ZFA:0000695 ! labial cavity
ZFA:0000151 ! pronephros        ZFA:0001438 ! coelom
ZFA:0000114 ! heart     ZFA:0001655 ! pericardial cavity
ZFA:0000076 ! swim bladder      ZFA:0001656 ! pleuroperitoneal cavity
ZFA:0000140 ! pancreas  ZFA:0001656 ! pleuroperitoneal cavity
ZFA:0000208 ! gall bladder      ZFA:0001656 ! pleuroperitoneal cavity
ZFA:0000413 ! gonad     ZFA:0001656 ! pleuroperitoneal cavity
ZFA:0000436 ! spleen    ZFA:0001656 ! pleuroperitoneal cavity
ZFA:0000529 ! kidney    ZFA:0001656 ! pleuroperitoneal cavity
ZFA:0005759 ! visceral fat      ZFA:0001656 ! pleuroperitoneal cavity
ZFA:0000166 ! lateral crista    ZFA:0000220 ! lateral semicircular canal
ZFA:0000225 ! lateral crista primordium ZFA:0000220 ! lateral semicircular canal
ZFA:0007055 ! pillar of the lateral semicircular canal  ZFA:0000220 ! lateral semicircular canal
ZFA:0000411 ! posterior crista primordium       ZFA:0000262 ! posterior semicircular canal
ZFA:0000566 ! posterior crista  ZFA:0000262 ! posterior semicircular canal
ZFA:0001672 ! dorsolateral septum       ZFA:0000262 ! posterior semicircular canal
ZFA:0007056 ! pillar of the posterior semicircular canal        ZFA:0000262 ! posterior semicircular canal
ZFA:0000468 ! anterior crista primordium        ZFA:0000314 ! anterior semicircular canal
ZFA:0000619 ! anterior crista   ZFA:0000314 ! anterior semicircular canal
ZFA:0001672 ! dorsolateral septum       ZFA:0000314 ! anterior semicircular canal
ZFA:0007054 ! pillar of the anterior semicircular canal ZFA:0000314 ! anterior semicircular canal

Which we corrected and asked you to run the preversion through the reasoners. You noted that there were no longer any complaints:

Sorry for the slow reply! Checking with the reasoner, I no longer see any complaints about material entities being parts of immaterial entities. To do the check I needed to import RO, then make ZFA ‘anatomical structure’ a subclass of CARO ‘anatomical structure’, and also ZFA ‘anatomical space’ a subclass of CARO ‘immaterial anatomical entity’.

I think it would be useful to include some bridge axioms to CARO like this when ZFA is used in Noctua; it will help with error checking. Such bridging is provided via the ZFA-to-Uberon bridge, but that bridging still results in many unsatisfiable classes (174). As long as we don’t bridge to Uberon, I think we can include ZFA into Noctua. It will be a bigger project if someone wants to resolve differences between Uberon and ZFA. So that’s why in the meantime I think a little ZFA-to-CARO bridge could be useful.

**Comment by balhoff** [comment]
@ybradford yes that's right, it was the 174 classes that become unhappy if the ZFA-to-Uberon bridge is included. If we don't include that bridge in Noctua then things are okay. Sorry, I forgot that we weren't necessarily including that. In that case creating a ZFA-to-CARO bridge might still be useful for error checking. Have you already made a release of ZFA with the immaterial/material changes?

**Comment by ybradford** [comment]
@balhoff  yes the latest version is available https://github.com/cerivs/zebrafish-anatomical-ontology

**Comment by balhoff** [comment]
I merged in the ZFA import to the Noctua ontology. It will take some time to show up in Noctua, waiting on a system restart (delayed by personnel vacations).

**Comment by kltm** [comment]
@balhoff This works on just a restart right? No other testing needed?

**Comment by balhoff** [comment]
Yes but I think an ontology release needs to happen first.

**Comment by cerivs** [comment]
Which ontology?  Newest ZFA went live a week ago.

**Comment by balhoff** [comment]
go-lego (for Noctua)

**Comment by vanaukenk** [comment]
This work has been done.
