### ISSUE TITLE
Delay in seeing cloned evidence in graph view

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#578]
Hi,
We've been working on a more complex model today and finding that there's sometimes been a delay in between the time that evidence was cloned for an edge/relation and when that evidence actually appears on the graph editor (both as a number in the evidence individual and in the reference display when you click on the upper left box in the relation).
When we haven't seen the evidence in the graph, we repeat the clone evidence action and then eventually wind up with duplicate (or more) evidence entries.
Any ideas on what could be happening?
The model we're working on is:
http://noctua.geneontology.org/editor/graph/gomodel:5b528b1100001416
Thanks,
--Kimberly and Marie-Claire

**Comment by kltm** [comment]
Communicating with @vanaukenk on a different channel, I have so far been unable to replicate this locally, although it has been apparently been replicated remotely.
If at all possible, could I get some step-by-step instructions for replication from the time of landing on the model, using a bogus piece of evidence (like and IEA, so I can undo it easily when finished).
Otherwise, it may be good to setup a time when we can be on the model together and I can view the activity.
