### ISSUE TITLE
Logout behavior

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#675]
Hi,

In testing the new Noctua landing page and moving around from one workbench to another, things seem to be working fine.

However, I'd like to confirm the expected outcome when logging out from one workbench on login status in another workbench.

For example, if I have the landing page, form, and graph editor open in separate tabs and logout from the graph editor, when I go back to the form, it looks like I'm still logged in, I can create a new activity, get a message that it's successfully updated, but that activity never appears on the right-hand table:

![image](https://user-images.githubusercontent.com/1730534/82672068-d3ca9b80-9c0d-11ea-9b94-080679cbfe7f.png)

I'd expect that if I logout from any workbench, I logout out from all of them and can no longer perform any actions.  

I'd also expect to see myself logged out from any other workbenches.

**Comment by kltm** [comment]
To clarify what's going on under the hood for context.

* a logout action sends a request to barista to destroy/de-issue a token
  * this is usually done by passing through a barista logout interface
* when an "editorial" command is sent to barista without a correct active token, barista should deny it with the response: `{ "message_type": "error", "message": "You are using a bad token; please remove it." }`.

I'm guess that there are two separate threads interacting here. The first is that while editorial events are passed around, login/logout events are not. This is the way many interfaces work and generally seem accepted by users as 1) you just logged out and 2) the next time you try something the interface will tell you that you are no longer logged in (both Google Docs and Amazon work like this).

My first guess would be that the response from the now gone token being used in the request isn't being picked up by the client, which is why the action triggers but has no effect. I think that everything you stated is the expected thing, up until "create a new activity, get a message that it's successfully update, but that activity never appears on the right-hand table".

**Comment by vanaukenk** [comment]
Thanks for the explanation @kltm   What you've said all makes sense.

Let's discuss this issue on tomorrow's workbenches call to see what a workable solution for alerting the curators that they're logged out (i.e. lost their token) before they try to edit from a workbench.

**Comment by vanaukenk** [comment]
@tmushayahama 
Enable error reporting when an editorial command is sent and denied due to logout.

More involved treatment of this issue, e.g. checking login/logout status when changing tabs or at each editorial step, will be split out into a separate noctua ticket.

**Comment by tmushayahama** [comment]
@kltm @lpalbou I ended up just removing the barista_token param and replace the window url. This can be used in noctua global then clients will update accordingly 

 vanilla js is something like 

```js

window.addEventListener('focus', focusFunction);
function focusFunction() {
    // Check if token is not valid (send request to user info by barista
    const url = new URL(window.location.href);
    url.searchParams.delete('barista_token');
    window.history.replaceState(null, null, url.href);
}
```

@vanaukenk after update you can check the 2 PRs above and test cases. Especially if the normal login is still working properly

**Comment by vanaukenk** [comment]
@tmushayahama 

I've tested several different scenarios for logging in and out of either the landing page or one of the workbenches (i.e. form or graph).

It seems to be working fine, i.e. if I logout of one workbench, the other workbenches are aware of that.  

However, for the curator, the login/logout status is immediately apparent in the form, but not in the graph editor.  For example, when I logout from the landing page and return to the form, I see the message that I'm no longer logged in.  When I go to the graph, it's not until I try to enter something, that I get an error message with a remote processing bar that I have an indication that I can no longer edit the model.

I think we discussed this at the last workbenches meeting, so I would put this in the category of providing a more uniform experience between the form and graph editors.  From the POV of the login/logout functionality, though, I think everything is working okay.

**Comment by tmushayahama** [comment]
@kltm the issue @vanaukenk posted above is that the logic works for only NF and landing page. I think the implementation should be at the noctua parent. or every workbench should implement this behavior (not ideally)

**Comment by lpalbou** [comment]
Solving it on noctua graph would be additional work indeed as both tools have been developed with very different architectures and expertises Still possible but I would suggest that to to be fixed later to avoid delaying the deployment in production of noctua LP. We will probably have to solve several user experience issues in the next months too

**Comment by kltm** [comment]
@vanaukenk If I'm remembering the issue correctly, it would be non-trivial to do this--the architectures and software used for different parts is very different. With the recent de-emphasis of the graph editor, it may not be worth pursuing separately. However, this has not been fixed, so I think closure is your call.

**Comment by vanaukenk** [comment]
Thanks @kltm 
I will close this ticket for now and remove the high priority label.
