### ISSUE TITLE
Update 'acts on population of' id from GOREL to RO ID

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua#684]
'acts on population of' is a relation available in the pop-up window of the graph editor.

We need to update its associated ontology id from GOREL:0001006 to RO:0012003.

Thx.

**Comment by kltm** [comment]
@vanaukenk 

Okay, sorry it took me so long to wrap my head around this. Basically, this is not part of the "embedded" (bad) widget that we have, but rather part of the list of *possible* relations that is returned from Minerva at startup--it is appended to the bottom of the hard-coded section to give users options. If this has already been fixed in the ontology, is should be as simple as a restart to have the changes appear in the interface.

```
acts_on_population_of (obo:GOREL_0001006)
```

**Comment by vanaukenk** [comment]
Done; corrected in Noctua graph editor.
