### ISSUE TITLE
Label for GO:0140582 not displayed in Noctua

### ISSUE THREAD

**Issue by pfey03** [geneontology/noctua#710]
GO:0140582 adenylate cyclase-activating G protein-coupled cAMP receptor signaling pathway
The term has been created on 1/30/21 and is available in QuickGo and AmiGO
The term does not display in Noctua graph or form. The term displays briefly when adding the ID but doesn't show up in final annotation. Here is the model with this process:
http://noctua.geneontology.org/editor/graph/gomodel:5fadbcf000001493

**Comment by pgaudet** [comment]
@kltm @balhoff 

Is the NEO /GO-LEGO issue resolved? I think no new GO terms were being loaded in Noctua since late 2020 due to some problem.

**Comment by kltm** [comment]
@pgaudet You're likely thinking of https://github.com/geneontology/neo/issues/62 ; that was completed a couple of weeks ago. However, I have a hunch that this is somehow a hangover from that.

Trying to duplicate the above issue does not work on noctua-dev--the term comes through in the autocomplete and in the minerva response:

![Screenshot from 2021-02-25 16-18-43](https://user-images.githubusercontent.com/2687900/109237082-ca1a2980-7785-11eb-9d07-8ba03b4e1176.png)
![Screenshot from 2021-02-25 16-20-44](https://user-images.githubusercontent.com/2687900/109237086-cb4b5680-7785-11eb-93c0-374cad7cf602.png)

I can, however, duplicate this on the production server.

My (unsubstantiated) guess is that the term was "used" before it was in the ontology and got stuck/cached in there without a label and it's been there ever since. @balhoff Does that sound reasonable/possible?

Tagging @vanaukenk what I'd like to do is cycle production and rebuild--like what we do during upgrades. If we're thinking longer term, maybe something added to minerva that would periodically retry looking up terms without labels (and purge its old "cache" (assuming that's coherent and what's going on here--big "if"s).

**Comment by pfey03** [comment]
@kltm I did not try the term before it was available in AmiGo and QuickGO.  And I don't know who else could have tried it.

**Comment by kltm** [comment]
@pfey03 In this case, we're interested in when it got into NEO (http://noctua-amigo.berkeleybop.org/amigo/search/ontology), rather than AmiGO or other sources.
NEO, due to issues with some upstream data (https://github.com/geneontology/neo/issues/62), was not building and refreshed until around 2021-02-18.

**Comment by balhoff** [comment]
@kltm how frequently are you updating the ontology loaded in Minerva?

**Comment by kltm** [comment]
@balhoff Very rarely. There have been no systematic restarts planned (something talked about previously with @vanaukenk, as well as looking at getting minerva to do it live w/Ben ), so essentially on large upgrades and power outages, etc.

**Comment by balhoff** [comment]
I think we need to do this much more often. This is the only way to get ontology updates.

**Comment by kltm** [comment]
@balhoff Agreed, but there has been no decided pattern and the jury was still out (from what I remember) on whether Minerva would be able to do this "hot". That last part though, I had thought we had a ticket, or some other written discussion about it, but I haven't found it yet. IIRC, it would be quite difficult, and in the meantime we were going to look at scheduling something, etc.

**Comment by vanaukenk** [comment]
@kltm 
If, wrt this particular issue, you'd like to schedule a planned production outage to update the ontologies, let's go ahead and do that.
In the long term, yes, we need to figure out what is a reasonable update schedule and how best to implement that. I suspect that for curators the most desirable update schedule is daily.

**Comment by pfey03** [comment]
@kltm I updated the term we cannot use for Dicty with the new term on Monday 2/22, a day before the GO-CAM meeting. It happened there, I demonstrated it on 2/23 at meeting.

**Comment by pfey03** [comment]
@vanaukenk Yes, not at the moment for myself but once we are fully in GO-CAM definitely, and several are using it for production already. Daily would be awesome.

**Comment by kltm** [comment]
@vanaukenk Yes, I'm looking to plan an outage to see if that fixes this.
For the future, if we are looking at a daily schedule, that is not something that I think we want to do "manually" at this point (fussy, requires a human, and knocks us out for an hour). I think weekly is doable for what we have now, but with the same caveats. Looking forward, I think we'll really want to build something more automated into the system.

**Comment by vanaukenk** [comment]
This has been fixed.
