### ISSUE TITLE
Contributor filter appears to be broken

### ISSUE THREAD

**Issue by cerivs** [geneontology/noctua#730]
When I select a contributor in the filter panel it looks like the filter is not working.  If I select my name nothing shows in the results pane.   When I look at most of the models the ORCiD is showning not the contributor name. If I find one of my models and click on the ORCID then I can find my models but it looks like there is nothing in the filter pane.  
![image](https://user-images.githubusercontent.com/2602957/126360617-949e60cf-8da1-4530-8c2d-97a7ecc8299f.png)
![image](https://user-images.githubusercontent.com/2602957/126361213-8925034d-a157-4923-8273-eeb77adbcf71.png)

**Comment by balhoff** [comment]
Probably a result of https://github.com/geneontology/go-site/pull/1710 (changed ORCIDS from http to https). The models still have the http version, but user names are linked to the https version. We need to migrate the Noctua models.

**Comment by kltm** [comment]
Hm. I'm not quite sure how this is happening, as we have not restarted production yet (planned for Thursday). I suppose there the form/ART might be pulling in the data from one of its own sources?

Pinging @vanaukenk

**Comment by kltm** [comment]
@cerivs @vanaukenk 
Okay I think I know how this data bug got through. If I'm correct about what's going on here, I believe I have half the mechanism about what is going on (and this one is on me). I'm still checking...
I had forgotten about the mechanism by which we add new users to the system: it essentially updates itself against `master` and does a refresh. This mechanism simplifies adding new users and keeping them up to date, but may be working against our testing timing for Thursday here. For the moment, I've reverted back to go-site  https://github.com/geneontology/go-site/tree/ce0bbbb2d9d72a5f319a7ef86955106af48f7a11on production. While the data is updated on the system, I'm a little unsure about how it got to the interface. @vanaukenk , have you done an admin refresh since we went http -> https?

**Comment by cerivs** [comment]
Looks like whatever you did allows me to filter by my name.  It does look like there is a weird mix of ORCIDs and Names in the Contributor field but my issue is fixed.

**Comment by tmushayahama** [comment]
@kltm @vanaukenk are you working on this? Anything on the UI side I need to do? it seems like some orcids are not getting resolved

**Comment by kltm** [comment]
@tmushayahama This should "naturally" resolve on Thursdays, after the planned outage.

**Comment by vanaukenk** [comment]
Closing this, as the underlying issue is fixed.
Note, however, that we still have #665 to address.
