### ISSUE TITLE
What is the current GO-CAM API algorithm for deciding if a model is "displayable" or not

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#757]
While we are waiting to complete https://github.com/geneontology/noctua/issues/746 , to help with debugging some issues, we wanted to clarify the details of the algorithm for displaying a model or not.

@sierra-moxon @dustine32 

Tagging @pgaudet

**Comment by sierra-moxon** [comment]
I took a cursory look through the[ SPARQL queries](https://github.com/geneontology/api-gorest/tree/master/queries) used to (I think?) get the data.  I have an example of a model that is shown (I'm assuming "displaying a model or not" is in reference to Alliance gene pages, right?), do you have an example model that is not shown?  This would help me track it down.

**Comment by kltm** [comment]
Cheers!
I believe that "human TBK1" is such an example (http://noctua.geneontology.org/editor/graph/gomodel:5f46c3b700001407), with the expectation that it would be displayed (from @pgaudet ).

**Comment by dustine32** [comment]
Here's the [query](https://github.com/geneontology/api-gorest-2021/blob/3f2e9958286a63c24cd8ce599c762e56b40f5eff/queries/sparql-gp.js#L67) that currently runs on the Alliance gene page.

Given a gene ID, it will return a model if:
1. The model has a chain of at least three functions connected by at least two consecutive causal relation edges
2. One of these functions is enabled_by this input gene

Just to clarify, a model containing one of these chains will not be returned if the query gene doesn't enable one of the "causal" functions.

@kltm Querying causal models for human genes like TBK1 from the Alliance site is tricky (i.e. doesn't work) right now because Noctua GO-CAM uses UniProt IDs for human and Alliance uses HGNC. This issue is described in [SCRUM-1064](https://agr-jira.atlassian.net/jira/software/c/projects/SCRUM/issues/SCRUM-1064).

**Comment by kltm** [comment]
@dustine32 Ah, interesting--thank you for the clarification!

**Comment by kltm** [comment]
I think we're good here?
