### ISSUE TITLE
Block annotations to root terms in GPAD output

### ISSUE THREAD

**Issue by hattrill** [geneontology/noctua#867]
In the Noctua snapshot gpad:
http://snapshot.geneontology.org/products/upstream_and_raw_data/index.html

there are annotations to root terms e.g. 
FB	FBgn0033814	enables	GO:0003674	GO_REF:GO_REF:0000015	ECO:0000307			20230829	FlyBase		model-state=production|noctua-model-id=gomodel:646ff70100003749|contributor=https://orcid.org/0000-0003-3212-6364

These should not be exported from Noctua.

Could annotations to root nodes 
GO:0005575
GO:0008150
GO:0003674
be blocked from the Noctua gpad output.

**Comment by vanaukenk** [comment]
@hattrill

We can't completely block root node annotations from the Noctua GPAD, since some of the groups, e.g. MGI, ZFIN, who use Noctua for all of their annotation have 'genuine' root node annotations that they want back out.

In looking at the model from the annotation in your comment, though, I'm wondering if what you wanted from these annotations was the statement that 'gene x' _is active in_ ' GO CC'.  In other words, were these meant to produce standard GO CC annotations?

Which annotation workbench, e.g. form, VPE, graph, was used to create these annotations?

Thx.

**Comment by hattrill** [comment]
@vanaukenk  
These would generally be ones where we have a model with BP and may be CC, but no clear mechanism in that situation. can I just delete these MF in form and have a "null" in the slot?

**Comment by vanaukenk** [comment]
@hattrill 

The rules haven't actually changed - if a root node annotation is in Noctua with the appropriate GO_REF:0000015, they will be exported.

What is _not_ exported are root node annotations that don't have GO_REF:0000015 as evidence, which are, for example, the MF root node annotations created when curators use the BP annotation interface of the Noctua form.

If you want to just make a standard CC annotation, I'd recommend using the CC annotation interface in the Noctua form where you can select _is active in_ as the gp2term relation and don't have to otherwise worry about the underlying GO-CAM data model.

This is exactly the kind of thing we hope to remedy with the new standard annotation UI, which should be available for more general testing in a few weeks.

**Comment by vanaukenk** [comment]
@hattrill 

If you want to go over this on today's annotation call, I'm happy to do that.

**Comment by hattrill** [comment]
Hi @vanaukenk if I remove the GO_REF:0000015?

**Comment by vanaukenk** [comment]
@hattrill 

Annotation Zoom?

**Comment by hattrill** [comment]
Nothing to fix
